apiVersion: v1
kind: Service
metadata:
  name: capston-service
spec:
  selector:
    app: capston
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capston
spec:
  selector:
    matchLabels:
      app: capston
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: capston
    spec:
      containers:
      - name: capston
        imagePullPolicy: Always
        image: docker.io/ehab123/capston:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
             path: /
             port: 80